<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Marks an AttributeFamily row as auto-generated by
 * LazadaAttributeFamilyGenerator::syncForCategory() for one specific Lazada
 * category — purely a lookup key so a re-sync can find-or-create the same
 * row idempotently (`AttributeFamily::firstOrNew(['lazada_category_id' =>
 * ...])`) instead of creating a duplicate Family every time an admin clicks
 * "สร้าง/อัปเดต Attribute Family". Null on every Family an admin created by
 * hand through the normal Attribute Family pages — this column plays no
 * role there.
 *
 * `unique()` enforces the idempotency this exists for: at most one
 * auto-generated Family per Lazada category, ever.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('attribute_families', function (Blueprint $table) {
            $table->foreignId('lazada_category_id')->nullable()->unique()->after('id')->constrained('lazada_categories')->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('attribute_families', function (Blueprint $table) {
            $table->dropForeign(['lazada_category_id']);
            $table->dropColumn('lazada_category_id');
        });
    }
};
