<?php

namespace App\Models;

use App\Models\Concerns\Auditable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Cache;

class AttributeFamily extends Model
{
    use Auditable;

    protected $with = ['translations'];

    protected function name(): \Illuminate\Database\Eloquent\Casts\Attribute
    {
        return \Illuminate\Database\Eloquent\Casts\Attribute::make(
            get: function ($value) {
                if ($this->relationLoaded('translations')) {
                    $localeId = \App\Models\Locale::idForCode(app()->getLocale());
                    if ($localeId) {
                        $translation = $this->translations->firstWhere('locale_id', $localeId);
                        if ($translation && !empty(trim((string) $translation->label))) {
                            return $translation->label;
                        }
                    }
                }
                return $value;
            }
        );
    }

    protected $fillable = [
        'code',
        'name',
        'lazada_category_id',
        'shopee_category_id',
        'tiktok_category_id',
        'created_by',
        'updated_by',
    ];

    /**
     * Non-null only on a Family auto-generated by
     * LazadaAttributeFamilyGenerator::syncForCategory() — purely a lookup
     * key so a re-sync finds this same row instead of creating a duplicate.
     * Null on every Family an admin created by hand.
     */
    public function lazadaCategory(): BelongsTo
    {
        return $this->belongsTo(LazadaCategory::class);
    }

    /**
     * Mirror ของ lazadaCategory() ด้านบน แต่สำหรับ Family ที่สร้างโดย
     * ShopeeAttributeFamilyGenerator::syncForCategory()
     */
    public function shopeeCategory(): BelongsTo
    {
        return $this->belongsTo(ShopeeCategory::class);
    }

    /**
     * Mirror ของ lazadaCategory()/shopeeCategory() ด้านบน แต่สำหรับ Family
     * ที่สร้างโดย TikTokAttributeFamilyGenerator::syncForCategory()
     */
    public function tiktokCategory(): BelongsTo
    {
        return $this->belongsTo(TikTokCategory::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updater(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    public function attributes(): BelongsToMany
    {
        return $this->belongsToMany(Attribute::class, 'family_attributes', 'family_id', 'attribute_id')
            ->using(FamilyAttribute::class)
            ->withPivot('attribute_group_id');
    }

    public function products(): HasMany
    {
        return $this->hasMany(Product::class, 'family_id');
    }

    /**
     * กลุ่มสินค้า (categories ที่ depth 3) ที่ผูกตระกูลนี้ไว้ — ดู
     * Category::attributeFamilies() ประกอบ (ฝั่งนั้นเป็นฝั่งหลักที่ถูกใช้จริง
     * จาก ProductGroupController; ฝั่งนี้ไว้เผื่อใครอยากไล่กลับจากตระกูลไปหา
     * กลุ่มสินค้าที่ผูกอยู่)
     */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class, 'category_attribute_family', 'family_id', 'category_id')
            ->withPivot('sort_order')
            ->orderByPivot('sort_order');
    }

    public function translations(): HasMany
    {
        return $this->hasMany(AttributeFamilyTranslation::class);
    }

    private const LIST_VERSION_KEY = 'attribute_families:list:version';

    /**
     * Cached id/code/name list for every family — used by
     * ProductController::index() to populate the grid's family filter
     * dropdown, previously re-queried on every grid page/sort/filter.
     * Invalidated on family CRUD — see
     * AttributeFamilyController::store()/update()/destroy().
     */
    public static function cachedList(): \Illuminate\Support\Collection
    {
        return Cache::rememberForever(
            'attribute_families.list:v'.static::listVersion(),
            fn () => static::select('id', 'code', 'name')->orderBy('name')->get()
        );
    }

    public static function listVersion(): int
    {
        return (int) Cache::get(self::LIST_VERSION_KEY, 1);
    }

    public static function bumpListVersion(): void
    {
        Cache::forever(self::LIST_VERSION_KEY, self::listVersion() + 1);
    }
}
