<?php

namespace App\Services\TikTok;

use App\Models\TikTokSellerAccount;
use Illuminate\Http\Client\Response;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use RuntimeException;

/**
 * Thin wrapper around TikTok Shop's Partner API. Confirmed against the real
 * docs pages shared for this session (open-api.tiktokglobalshop.com,
 * "Get Categories" — GET /product/{version}/categories): the base URL, path
 * shape, required header (x-tts-access-token — a header, unlike Lazada/
 * Shopee which pass their token in the query string/form body), and that
 * every call needs app_key/timestamp/sign/shop_cipher as query params.
 *
 * NOT confirmed: the exact signing algorithm. The shared docs page only
 * describes `sign` as "Signature generated by gen algorithm" — no worked
 * example or algorithm spec was included. sign() below follows TikTok
 * Partner API's publicly documented v2 signing scheme (sort query params
 * excluding sign/access_token, concatenate as path+key+value pairs, wrap
 * with app_secret, HMAC-SHA256 keyed by app_secret) from general knowledge
 * of this API family — same status as LazadaClient::createProduct() before
 * its first live call: treat as "needs live verification", not settled
 * fact, until a real call against a real shop confirms it. Also unconfirmed
 * here (not shown in the shared docs): whether TIKTOK_APP_KEY/
 * TIKTOK_APP_SECRET (config/services.php) have real values at all — this
 * client cannot make a single successful call without them.
 */
class TikTokClient
{
    private string $baseUrl;

    private string $appKey;

    private string $appSecret;

    public function __construct(private readonly TikTokSellerAccount $account)
    {
        $this->baseUrl = config('services.tiktok.base_url');

        // Fails here with a clear, actionable message instead of further
        // down as a cryptic "Cannot assign null to property ... of type
        // string" — these two have no default in config/services.php (no
        // sane one exists for a secret) and are still unset in .env as of
        // this writing.
        $this->appKey = config('services.tiktok.app_key')
            ?: throw new RuntimeException('TIKTOK_APP_KEY is not set in .env — get it from TikTok Shop Partner Center and add it before syncing TikTok categories/products.');
        $this->appSecret = config('services.tiktok.app_secret')
            ?: throw new RuntimeException('TIKTOK_APP_SECRET is not set in .env — get it from TikTok Shop Partner Center and add it before syncing TikTok categories/products.');
    }

    /**
     * GET /product/{version}/categories — confirmed shape from the shared
     * docs: flat `data.categories[]`, each {id, parent_id, local_name,
     * is_leaf, permission_statuses}. `202309` is the API version segment
     * used in the docs' own curl example — not confirmed whether a newer
     * version exists/is preferred, kept as a param in case it needs to
     * change later without touching call sites.
     */
    public function getCategoryTree(string $categoryVersion = 'v2', string $locale = 'th-TH', string $apiVersion = '202309'): array
    {
        return $this->request("/product/{$apiVersion}/categories", [
            'category_version' => $categoryVersion,
            'locale' => $locale,
        ]);
    }

    private function request(string $apiPath, array $params = []): array
    {
        $query = $this->signedParams($apiPath, $params);

        // timeout()/retry() from day one (see ShopeeClient/LazadaClient,
        // which only got these added after already shipping without them)
        // — retry() only fires on connection-level failures since
        // handleResponse() below doesn't throw on TikTok's own error codes.
        $response = Http::timeout(30)->retry(2, 200)
            ->withHeaders([
                'content-type' => 'application/json',
                'x-tts-access-token' => $this->account->access_token,
            ])
            ->get($this->baseUrl.$apiPath, $query);

        return $this->handleResponse($response, $apiPath);
    }

    /**
     * app_key/timestamp/shop_cipher/sign — required on every call per the
     * shared docs' "Query" table. shop_cipher comes from this account's own
     * n8n row (TikTokSellerAccount::$shops_cipher), not a fixed app-level
     * value — each connected shop has its own.
     */
    private function signedParams(string $apiPath, array $params): array
    {
        $params['app_key'] = $this->appKey;
        $params['timestamp'] = time();
        $params['shop_cipher'] = $this->account->shops_cipher;
        $params['sign'] = $this->sign($apiPath, $params);

        return $params;
    }

    /**
     * NOT CONFIRMED LIVE — see class docblock. Sort params (excluding sign/
     * access_token) by key, concatenate as "{key}{value}{key}{value}...",
     * prefix with the API path, wrap with app_secret on both sides, then
     * HMAC-SHA256 keyed by app_secret, lowercase hex.
     */
    private function sign(string $apiPath, array $params): string
    {
        unset($params['sign'], $params['access_token']);
        ksort($params);

        $base = $apiPath;
        foreach ($params as $key => $value) {
            $base .= $key.$value;
        }

        $input = $this->appSecret.$base.$this->appSecret;

        return hash_hmac('sha256', $input, $this->appSecret);
    }

    private function handleResponse(Response $response, string $apiPath): array
    {
        $data = $response->json();

        if ($data === null) {
            throw new RuntimeException("TikTok API returned a non-JSON response (HTTP {$response->status()}): ".$response->body());
        }

        if (($data['code'] ?? 0) !== 0) {
            Log::error('TikTok API error', [
                'api_path' => $apiPath,
                'response' => $data,
            ]);

            throw new RuntimeException(
                "TikTok API error [{$data['code']}]: ".($data['message'] ?? 'unknown error')
            );
        }

        return $data;
    }
}
